version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
      - ../.env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  telegram-budget:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    command: bash -c "alembic upgrade head && python main.py"
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  db_data:
    driver: local
