"""first migration1

Revision ID: 6136c20cae6e
Revises: 640c4625dc98
Create Date: 2023-10-30 11:30:09.518092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6136c20cae6e'
down_revision: Union[str, None] = '640c4625dc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='alias')
    op.drop_index('title_2', table_name='alias')
    op.drop_index('title_3', table_name='alias')
    op.drop_index('title_4', table_name='alias')
    op.drop_index('title_5', table_name='alias')
    op.drop_index('title_6', table_name='alias')
    op.drop_index('title_7', table_name='alias')
    op.drop_index('title', table_name='category')
    op.drop_index('title_2', table_name='category')
    op.drop_index('title_3', table_name='category')
    op.drop_index('title_4', table_name='category')
    op.drop_index('title_5', table_name='category')
    op.drop_index('title_6', table_name='category')
    op.drop_index('title_7', table_name='category')
    op.create_foreign_key(None, 'transaction', 'alias', ['alias_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_index('title_7', 'category', ['title'], unique=False)
    op.create_index('title_6', 'category', ['title'], unique=False)
    op.create_index('title_5', 'category', ['title'], unique=False)
    op.create_index('title_4', 'category', ['title'], unique=False)
    op.create_index('title_3', 'category', ['title'], unique=False)
    op.create_index('title_2', 'category', ['title'], unique=False)
    op.create_index('title', 'category', ['title'], unique=False)
    op.create_index('title_7', 'alias', ['title'], unique=False)
    op.create_index('title_6', 'alias', ['title'], unique=False)
    op.create_index('title_5', 'alias', ['title'], unique=False)
    op.create_index('title_4', 'alias', ['title'], unique=False)
    op.create_index('title_3', 'alias', ['title'], unique=False)
    op.create_index('title_2', 'alias', ['title'], unique=False)
    op.create_index('title', 'alias', ['title'], unique=False)
    # ### end Alembic commands ###
