"""Del useless User fields

Revision ID: 7e8d62dd19ef
Revises: d23e9f9c4250
Create Date: 2023-10-24 17:24:39.880634

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e8d62dd19ef'
down_revision: Union[str, None] = 'd23e9f9c4250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('description', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
