"""Add cascade delete transactions

Revision ID: ea12f5002ccd
Revises: cdd104e2ae5b
Create Date: 2023-11-01 09:55:36.568976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea12f5002ccd'
down_revision: Union[str, None] = 'cdd104e2ae5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
